name: Deploy GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Pages
        uses: actions/configure-pages@1f9a2e6f47738f654b702ec9f448b111166649f8 # v5.0.0
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3d70d9ad4b7c0cb20e9641 # v3.0.1
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90154ac5ed86848d487525533a96e277edc4 # v4.0.5
